IP_SERVER = 'www.sotouch.com';
GROUPE_SUPER_ADMIN = 1;
GROUPE_ADMIN       = 2;
GROUPE_USER        = 3;

MEDIA_SUFFIX_1=".JPG";
MEDIA_SUFFIX_2=".JPEG";
MEDIA_SUFFIX_3=".GIF";
MEDIA_SUFFIX_4=".PNG";
MEDIA_SUFFIX_5=".MOV";
MEDIA_SUFFIX_6=".FLV";
MEDIA_SUFFIX_7=".MP4";
MEDIA_SUFFIX_8=".SWF";
MEDIA_SUFFIX_9=".ZIP";
