package com.sotouch.myway.view.action.map;

import javax.annotation.Resource;

import org.hurryapp.fwk.annotation.Unsecured;
import org.hurryapp.fwk.view.action.BaseAction;

import com.sotouch.myway.service.map.MapService;
import com.sotouch.myway.view.action.item.ItemViewBean;

@Unsecured
public class MapAction extends BaseAction<ItemViewBean> {

	protected Integer project_id;
	protected String publish_mode;

	private String xml;
	private String paths;

	@Resource (name="mapService")
	private MapService mapService;

	@Override
	protected void doExecute() throws Exception {
	}

	@Override
	protected void doInit() throws Exception {
	}

	/**
	 * Generate XML stream for map editor
	 * @return
	 * @throws Exception
	 */
	public String initEditor() throws Exception {
		xml = mapService.init(project_id, request.getContextPath());
		setXmlResponse(xml);
		return SUCCESS_XML;
	}

	/**
	 * Save item's positions and paths from the XML generated by the map editor
	 * @return
	 * @throws Exception
	 */
	public String saveEditor() throws Exception {
		mapService.save(project_id, xml);
		setXmlResponse("<success>OK</success>");
		return SUCCESS_XML;
	}
	
	/**
	 * Generate the project.xml file used by the terminals
	 * @return
	 * @throws Exception
	 */
	public String publishProject() throws Exception {
		mapService.export(project_id, publish_mode, paths, request.getContextPath());
		setXmlResponse("<success>OK</success>");
		return SUCCESS_XML;
	}
	
	/**
	 * List the project items
	 * @return
	 * @throws Exception
	 */
	public String listItems() throws Exception {
		xml = mapService.listItems(project_id);
		setXmlResponse(xml);
		return SUCCESS_XML;
	}

	//=========================================================================
	// ACCESSORS
	//=========================================================================
	public Integer getProject_id() {
		return project_id;
	}
	public void setProject_id(Integer projectId) {
		project_id = projectId;
	}

	public String getPublish_mode() {
		return publish_mode;
	}
	public void setPublish_mode(String publish_mode) {
		this.publish_mode = publish_mode;
	}

	public String getXml() {
		return xml;
	}
	public void setXml(String xml) {
		this.xml = xml;
	}

	public String getPaths() {
		return paths;
	}
	public void setPaths(String paths) {
		this.paths = paths;
	}
}
